### ISSUE TITLE
[Tagging] UX Refinements from Sandbox Round 1

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#157] opened 2023-11-29 19:19 UTC
Changes we've collected from initial testing:

### On `edx-platform`

1. [Comment](https://github.com/openedx/modular-learning/issues/118#issuecomment-1829635727): "Please change the order of the items in the unit menu to:" 
   - Configure
   - Manage tags
   - Copy to clipboard
   - Duplicate
   - Delete
1. [Comment](https://github.com/openedx/modular-learning/issues/120#issuecomment-1829706783): "Please change the order of the items in the component menu to:"
   - Manage Access
   - Move
   - Manage tags
   - Copy to Clipboard
   - Duplicate
   - Delete
1. [Comment](https://github.com/openedx/modular-learning/issues/120#issuecomment-1829706783): "There is a strange 'jump' when I first expand the "Tags" sidebar component. The area containing the "Tags" heading, tag count, and up/down arrow seems to shift down a few pixels when it is first clicked"
2. [Comment](https://github.com/openedx/modular-learning/issues/120#issuecomment-1829706783): This section also shows a dotted outline after it is selected (see screenshot below):
   <img width="321" alt="Screenshot 2023-11-28 at 13 49 39" src="https://github.com/openedx/modular-learning/assets/88187719/a2162031-fa92-453a-a728-d745e18c6f21">
    - Note: it is important that this element is keyboard focusable and when it is focused using they keyboard, some visual outline must appear. We want to preserve that but also to not show that outline when it's clicked using the mouse. This can be achieved using `:focus-visible`.
1. [Comment](https://github.com/openedx/modular-learning/issues/120#issuecomment-1829706783): "If a tag cannot be expanded (i.e. leaf tags), it should not have a hover state (in the screenshot below, "flat taxonomy tag 2949" should be black, not blue):"
    <img width="211" alt="Screenshot 2023-11-28 at 14 00 00" src="https://github.com/openedx/modular-learning/assets/88187719/369783d5-c552-4981-b908-e72eae92b587">
1. ~~Slack: Refresh the count of tags on the unit/outline page(s) after the user makes edits in the tag drawer~~ 
   - Moved to #167
1. Change the default URL for the "Taxonomies" tab to go to `/taxonomies/` directly, not `/taxonomy-list/`

### Within the `course-authoring` MFE

1. [Comment](https://github.com/openedx/modular-learning/issues/104#issuecomment-1829447993): On the taxonomies list, display the full name of taxonomies in a tooltip if it's longer than what's displayed
3. [Comment](https://github.com/openedx/modular-learning/issues/138#issuecomment-1829742575): On the taxonomy detail page, please change the title of the "Value" column to "Tag name" https://github.com/openedx/modular-learning/issues/138
4. [Comment](https://github.com/openedx/modular-learning/issues/112#issuecomment-1827412152): On taxonomy detail page, remove the "child tags" column and put it in parentheses instead 
5. [Comment](https://github.com/openedx/modular-learning/issues/105#issuecomment-1829412705) - several minor issues. See link.
6. Slack: Make your browser window short (not too tall). From the Taxonomy List page, scroll down and click on "WGU" taxonomy. The taxonomy detail page loads, but it is already scrolled down. It should load with scroll=0. Figure out why react-router isn't properly resetting the scroll to 0 when clicking a link, as it should do for every page transition.
7. Slack: On [this page](https://cms.tagging-preview.staging.do.opencraft.hosting/container/block-v1:Axim+WGU_Sample1+Test_1+type@vertical+block@51f3f076232c48699224f6e61e7a821c#), clicking "Manage Tags" for a component (not the unit) that has no tags, then clicking Add Tags at the top makes the list of tags appear offscreen.
    * ![Screenshot 2023-12-01 at 9 57 28 AM](https://github.com/openedx/modular-learning/assets/945577/a4d681e1-c1fe-453b-9498-db194d17899f)
    * then the tag list gets cut off at the top: 
       ![Screenshot 2023-12-01 at 9 57 44 AM](https://github.com/openedx/modular-learning/assets/945577/aa4ca2a9-dc93-40e4-9fc2-4d9b9bbe87a8)

### To consider for the future (out of scope for now)

* We're only showing the number of "child" tags, not the total number of "child+grandchild+etc." tags, which doesn't match the designs. I think we'll probably need to change that at some point, but that's not as simple a change.

**Comment by bradenmacdonald** [comment] 2023-12-01 18:46
@ChrisChV  You probably noticed this, but I've been adding a few additional little issues to this ticket as they come in. If there are too many to address within one sprint/task, feel free to leave some of them for next sprint.

**Comment by ali-hugo** [comment] 2023-12-05 09:14
@bradenmacdonald 
> Probably because the numbers are currently grey for the child/grandchild tag counts on the sandbox.

Yip, that's it! They're actually supposed to be dark grey.

@ChrisChV I see that the colour that's currently being used for the child/grandchild numbers fails an accessibility check (when it appears on the grey rows of the table). Could you change all the numbers (the ones next to the child/grandchild tags, and the ones next to the parent tags) to #454545 please?

<img width="730" alt="Screenshot 2023-12-05 at 11 11 23" src="https://github.com/openedx/modular-learning/assets/88187719/61772637-6af6-4b25-b9a0-acda32d9452e">

**Comment by ChrisChV** [comment] 2023-12-05 15:28
> Slack: On [this page](https://cms.tagging-preview.staging.do.opencraft.hosting/container/block-v1:Axim+WGU_Sample1+Test_1+type@vertical+block@51f3f076232c48699224f6e61e7a821c#), clicking "Manage Tags" for a component (not the unit) that has no tags, then clicking Add Tags at the top makes the list of tags appear offscreen.

@yusuf-musleh This bug has been introduced in your PR https://github.com/openedx/frontend-app-course-authoring/pull/704
Only happens in your branch and in the sandbox that is updated also with your changes. If it's a quick change, can you fix it? or maybe it's better to fix it in another round of refinements? CC @bradenmacdonald

**Comment by ali-hugo** [comment] 2023-12-06 06:58
@rpenido @ChrisChV I'm CC-ing you both as I'm not sure who would work on the changes I've requested below. Please let me know if I should move this request elsewhere:

When testing on the sandbox yesterday, I noticed there was something missing from the importing/re-importing flow in the design for the taxonomy list page: there is no indication to the user that the taxonomy is being imported/re-imported. 

Could we add a [spinner](https://paragon-openedx.netlify.app/components/spinner/) to the card of the taxonomy that is being imported/re-imported? Like so (I thought it might be neater to place the icon to the left of the title since longer titles sometimes have ellipses to the right):

![Screenshot 2023-12-06 at 08 44 15](https://github.com/openedx/modular-learning/assets/88187719/5b51f654-f565-4bcd-a10e-2440fd7866ff)

Could we also add a [toast](https://paragon-openedx.netlify.app/components/toast/) to the bottom of the page?:

![Screenshot 2023-12-06 at 08 44 25](https://github.com/openedx/modular-learning/assets/88187719/92e1c250-9ef6-4405-b10e-62edd1dc16a0)

I think that would help to keep the user updated on what's happening.

CC @bradenmacdonald

**Comment by yusuf-musleh** [comment] 2023-12-06 12:33
> > 6. Slack: On [this page](https://cms.tagging-preview.staging.do.opencraft.hosting/container/block-v1:Axim+WGU_Sample1+Test_1+type@vertical+block@51f3f076232c48699224f6e61e7a821c#), clicking "Manage Tags" for a component (not the unit) that has no tags, then clicking Add Tags at the top makes the list of tags appear offscreen.
> 
> @yusuf-musleh This bug has been introduced in your PR [openedx/frontend-app-course-authoring#704](https://github.com/openedx/frontend-app-course-authoring/pull/704) Only happens in your branch and in the sandbox that is updated also with your changes. If it's a quick change, can you fix it? or maybe it's better to fix it in another round of refinements? CC @bradenmacdonald

@ChrisChV Thanks for pointing it out. I managed to reproduce it as well. The `ModalPopup` in Paragon has been a bit flaky in the placement, I've been having a hard time getting it to work properly, especially in these edge cases. Adding the `hasArrow` prop fixes this, however brings back another 2 issues [mentioned before](https://tasks.opencraft.com/browse/FAL-3530?focusedCommentId=280387&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-280387):

1. _The popup jumping around when adding/removing tags._ This can be fixed when we change the implementation to add/remove the actual tags when the popup is closed vs when on the fly when checking/unchecking tags
2. _The arrow's placement is off._ This is an issue in Paragon as well, but we can set the arrow to be `visibility: hidden` for it to now show for now, and create an issue in Paragon repo so a fix can be worked on later.

I think I can include a fix for it as part of my PR, essentially including the `hasArrow` prop, hiding the arrow, and changing the implementation to update the tags when the popup modal is closed rather than on the fly.

**Comment by rpenido** [comment] 2023-12-06 13:58
> @rpenido @ChrisChV I'm CC-ing you both as I'm not sure who would work on the changes I've requested below. Please let me know if I should move this request elsewhere:
> 
> When testing on the sandbox yesterday, I noticed there was something missing from the importing/re-importing flow in the design for the taxonomy list page: there is no indication to the user that the taxonomy is being imported/re-imported.
> 
> Could we add a [spinner](https://paragon-openedx.netlify.app/components/spinner/) to the card of the taxonomy that is being imported/re-imported? Like so (I thought it might be neater to place the icon to the left of the title since longer titles sometimes have ellipses to the right):
> 
> ![Screenshot 2023-12-06 at 08 44 15](https://private-user-images.githubusercontent.com/88187719/288313822-5b51f654-f565-4bcd-a10e-2440fd7866ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NzA4MDYsIm5iZiI6MTcwMTg3MDUwNiwicGF0aCI6Ii84ODE4NzcxOS8yODgzMTM4MjItNWI1MWY2NTQtZjU2NS00YmNkLWExMGUtMjQ0MGZkNzg2NmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDEzNDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMmNiYTAwYjFiNzc1NTBiYWY0NmNhN2ZmN2RlN2M1ZDAwYjAxOGJjNTI2Y2JmOTg4MzM2ZThkM2RhNGJiNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KIYQ76zW8uXgbud-EUBTJQgJ8R-7b_3VyAB8ib64YKE)
> 
> Could we also add a [toast](https://paragon-openedx.netlify.app/components/toast/) to the bottom left of the page?:
> 
> ![Screenshot 2023-12-06 at 08 44 25](https://private-user-images.githubusercontent.com/88187719/288314119-92e1c250-9ef6-4405-b10e-62edd1dc16a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NzA4MDYsIm5iZiI6MTcwMTg3MDUwNiwicGF0aCI6Ii84ODE4NzcxOS8yODgzMTQxMTktOTJlMWMyNTAtOWVmNi00NDA1LWIxMGUtNjJlZGQxZGMxNmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDEzNDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5ZTcyZGI1NmE3MTE0ODJlZTJjNjQ3ODVlOWRmY2YxMDBkZWRhMzY4YzUyNTgxYzYyZGY3ZjVjYWRmZmViYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GLSvPgIcI8K-IppP1GkPa2xUm7ec2jOvnon_8K1L0Q0)
> 
> I think that would help to keep the user updated on what's happening.
> 
 Hi @ali-hugo! For now, we are running the import tag synchronously, so as soon as the dialog is closed, the tag will be imported.
I will add a `Toast` as part of https://github.com/openedx/modular-learning/issues/126. 

![import_tags](https://github.com/openedx/modular-learning/assets/849463/51ec8ddc-24a7-4532-8d9a-9e4f21d4f85e)

I added `LoadingButtons` to the operations that do some work on the server.

PS: The design is a bit different than the wireframes. I will discuss it with you in the issue https://github.com/openedx/modular-learning/issues/126 soon!

**Comment by yusuf-musleh** [comment] 2023-12-07 09:25
> > 6. Slack: Refresh the count of tags on the unit/outline page(s) after the user makes edits in the tag drawer
> >    only if easy to do. Do not spend a lot of time on this now, as it will basically happen automatically in the new MFE version of these pages, thanks to using react-query.
> 
> @bradenmacdonald I can't fix this issue because [openedx/frontend-app-course-authoring#704](https://github.com/openedx/frontend-app-course-authoring/pull/704) is still open. FYI @yusuf-musleh


@ChrisChV Should be merged soon, awaiting final review from @xitij2000.

**Comment by bradenmacdonald** [comment] 2023-12-07 18:18
@ChrisChV That's OK, if one or two things are blocked or not possible to fit into this sprint, we can move them to a future ticket. As long as we don't lose track of them.

**Comment by ChrisChV** [comment] 2023-12-19 14:21
> @ChrisChV That's OK, if one or two things are blocked or not possible to fit into this sprint, we can move them to a future ticket. As long as we don't lose track of them.

Is there another ticket to add these remaining issues?

**Comment by ChrisChV** [comment] 2023-12-19 14:21
@bradenmacdonald ^

**Comment by bradenmacdonald** [comment] 2023-12-19 20:54
@ChrisChV Please add them here: https://github.com/openedx/modular-learning/issues/167

**Closed** 2024-01-08 22:09 UTC
